version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
        reservations:
          memory: 100M
    restart: always
  redis:
    image: redis:5.0.9-buster
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          memory: 25M
    restart: always
  nginx:
    image: jeffreyca/spleeter-web-nginx:latest
    volumes:
      - staticfiles:/webapp/staticfiles
    depends_on:
      - api
  api:
    image: jeffreyca/spleeter-web-api:latest
    volumes:
      - assets:/webapp/frontend/assets
      - staticfiles:/webapp/staticfiles
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=django_react.settings_docker
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - APP_HOST
      - AZURE_ACCOUNT_KEY
      - AZURE_ACCOUNT_NAME
    depends_on:
      - db
      - redis
      - frontend
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          memory: 1G
    restart: always
  frontend:
    image: jeffreyca/spleeter-web-frontend:latest
    volumes:
      - assets:/webapp/frontend/assets
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          memory: 500M
    restart: always
  huey:
    image: jeffreyca/spleeter-web-huey:latest
    entrypoint: ./huey-entrypoint.sh
    volumes:
      - pretrained-models:/webapp/pretrained_models
    environment:
      - DJANGO_SETTINGS_MODULE=django_react.settings_docker
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - APP_HOST
      - AZURE_ACCOUNT_KEY
      - AZURE_ACCOUNT_NAME
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G
    restart: always
volumes:
  pg-data:
  redis-data:
  pretrained-models:
  assets:
  staticfiles:
