version: '3.3'
services:
  db:
  redis:
  api:
    build: .
    volumes:
      - ./api:/webapp/api
      - ./media:/webapp/media
    environment:
      - DJANGO_DEVELOPMENT
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/webapp/frontend/src
  huey:
    build:
      context: .
    volumes:
      - ./api:/webapp/api
      - ./media:/webapp/media
    environment:
      - DJANGO_DEVELOPMENT
